### ISSUE TITLE
TypeError: Selector.get() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by djanym** [yshalsager/shamela2epub#222]
Salam alaykum.
I'm getting this error:
```
python3 -m shamela2epub download "https://shamela.ws/book/4445"
2023-12-10 02:44:06,834 [INFO] shamela2epub.cli.app [app.download:22]: Got valid URL: https://shamela.ws/book/4445
2023-12-10 02:44:57,573 [INFO] shamela2epub.cli.app [app.download:24]: Working on book كتاب البداية والنهاية ت التركي by ابن كثير
Downloading: 0 page [00:00, ? page/s]Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Volumes/ExtOWC/OTHER/shamela2epub/shamela2epub/shamela2epub/__main__.py", line 22, in <module>
    main()
  File "/Volumes/ExtOWC/OTHER/shamela2epub/shamela2epub/shamela2epub/__main__.py", line 18, in main
    click_cli()
  File "/Volumes/ExtOWC/OTHER/shamela2epub/shamela2epub/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/ExtOWC/OTHER/shamela2epub/shamela2epub/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Volumes/ExtOWC/OTHER/shamela2epub/shamela2epub/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/ExtOWC/OTHER/shamela2epub/shamela2epub/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/ExtOWC/OTHER/shamela2epub/shamela2epub/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/ExtOWC/OTHER/shamela2epub/shamela2epub/shamela2epub/cli/app.py", line 27, in download
    downloader.download()
  File "/Volumes/ExtOWC/OTHER/shamela2epub/shamela2epub/shamela2epub/main.py", line 60, in download
    self.create_first_page()
  File "/Volumes/ExtOWC/OTHER/shamela2epub/shamela2epub/shamela2epub/main.py", line 42, in create_first_page
    self.epub_book.set_parts_map(book_html_page.parts_map)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/ExtOWC/OTHER/shamela2epub/shamela2epub/shamela2epub/models/book_html_page.py", line 128, in parts_map
    {
  File "/Volumes/ExtOWC/OTHER/shamela2epub/shamela2epub/shamela2epub/models/book_html_page.py", line 129, in <dictcomp>
    part.get(""): index
    ^^^^^^^^^^^^
TypeError: Selector.get() takes 1 positional argument but 2 were given
Downloading: 0 page [00:50, ? page/s]

```

I'm using MacOS. The commands are running via Python Virtual Environment.

**Comment by yshalsager** [comment]
@djanym Fixed. Please update to latest. Thanks for reporting

**Comment by djanym** [comment]
By the way, adding a note in installation instructions about using Python Virtual Environment would be great. Because there are a lot of dependencies that throw errors in case something is not installed or the version is not suitable.
Like this:

1. (Recommended) Create a Python virtual environment: You can follow the [Python official documentation](https://docs.python.org/3/tutorial/venv.html) for virtual environments.

`python3 -m venv venv`

2. Activate the virtual environment:

- On Windows:

`.\venv\Scripts\activate`

- On macOS and Linux:

`source venv/bin/activate`

- for fish or:

`source venv/bin/activate.fish`

3. Install the required Python packages from requirements.txt:

`pip install -r requirements.txt`

.....

**Comment by yshalsager** [comment]
> By the way, adding a note in installation instructions about using Python Virtual Environment would be great. Because there are a lot of dependencies that throw errors in case something is not installed or the version is not suitable.

Yeah, feel free to open a pull request. I should add installing using pipx instructions too.
